// Generated by the protocol buffer compiler.  DO NOT EDIT!

package eco.ttc.proto.nano;

@SuppressWarnings("hiding")
public interface Common {

  public static final class Request extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Request[] _emptyArray;
    public static Request[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request[0];
          }
        }
      }
      return _emptyArray;
    }

    // string userId = 1;
    public String userId;

    // int32 cmdId = 2;
    public int cmdId;

    // int32 release = 3;
    public int release;

    // int32 platform = 4;
    public int platform;

    // int32 language = 5;
    public int language;

    public Request() {
      clear();
    }

    public Request clear() {
      userId = "";
      cmdId = 0;
      release = 0;
      platform = 0;
      language = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.userId.equals("")) {
        output.writeString(1, this.userId);
      }
      if (this.cmdId != 0) {
        output.writeInt32(2, this.cmdId);
      }
      if (this.release != 0) {
        output.writeInt32(3, this.release);
      }
      if (this.platform != 0) {
        output.writeInt32(4, this.platform);
      }
      if (this.language != 0) {
        output.writeInt32(5, this.language);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.userId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.userId);
      }
      if (this.cmdId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.cmdId);
      }
      if (this.release != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.release);
      }
      if (this.platform != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.platform);
      }
      if (this.language != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.language);
      }
      return size;
    }

    @Override
    public Request mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.userId = input.readString();
            break;
          }
          case 16: {
            this.cmdId = input.readInt32();
            break;
          }
          case 24: {
            this.release = input.readInt32();
            break;
          }
          case 32: {
            this.platform = input.readInt32();
            break;
          }
          case 40: {
            this.language = input.readInt32();
            break;
          }
        }
      }
    }

    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request(), data);
    }

    public static Request parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request().mergeFrom(input);
    }
  }

  public static final class Response extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Response[] _emptyArray;
    public static Response[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response[0];
          }
        }
      }
      return _emptyArray;
    }

    // int32 code = 1;
    public int code;

    // string message = 2;
    public String message;

    // int32 cmdId = 3;
    public int cmdId;

    // int64 timestamp = 4;
    public long timestamp;

    // string userId = 5;
    public String userId;

    public Response() {
      clear();
    }

    public Response clear() {
      code = 0;
      message = "";
      cmdId = 0;
      timestamp = 0L;
      userId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != 0) {
        output.writeInt32(1, this.code);
      }
      if (!this.message.equals("")) {
        output.writeString(2, this.message);
      }
      if (this.cmdId != 0) {
        output.writeInt32(3, this.cmdId);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(4, this.timestamp);
      }
      if (!this.userId.equals("")) {
        output.writeString(5, this.userId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.code);
      }
      if (!this.message.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.message);
      }
      if (this.cmdId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.cmdId);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.timestamp);
      }
      if (!this.userId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.userId);
      }
      return size;
    }

    @Override
    public Response mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.code = input.readInt32();
            break;
          }
          case 18: {
            this.message = input.readString();
            break;
          }
          case 24: {
            this.cmdId = input.readInt32();
            break;
          }
          case 32: {
            this.timestamp = input.readInt64();
            break;
          }
          case 42: {
            this.userId = input.readString();
            break;
          }
        }
      }
    }

    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response(), data);
    }

    public static Response parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response().mergeFrom(input);
    }
  }

  public static final class TransactionInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TransactionInfo[] _emptyArray;
    public static TransactionInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TransactionInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // int32 billType = 1;
    public int billType;

    // string transactionValue = 2;
    public String transactionValue;

    // string transactionFrom = 3;
    public String transactionFrom;

    // string transactionTo = 4;
    public String transactionTo;

    // uint32 gasLimit = 5;
    public int gasLimit;

    // string gasPrice = 6;
    public String gasPrice;

    // int64 timestamp = 7;
    public long timestamp;

    // int32 category = 8;
    public int category;

    // string description = 9;
    public String description;

    // int32 transactionRes = 10;
    public int transactionRes;

    // uint64 blockNumber = 11;
    public long blockNumber;

    // string txHash = 12;
    public String txHash;

    // string errMsg = 13;
    public String errMsg;

    // string extraData = 14;
    public String extraData;

    // int32 tid = 15;
    public int tid;

    // string remark = 16;
    public String remark;

    // string addressAlias = 17;
    public String addressAlias;

    // string tokenSymbol = 18;
    public String tokenSymbol;

    // int32 tokenId = 19;
    public int tokenId;

    // string tokenValue = 20;
    public String tokenValue;

    public TransactionInfo() {
      clear();
    }

    public TransactionInfo clear() {
      billType = 0;
      transactionValue = "";
      transactionFrom = "";
      transactionTo = "";
      gasLimit = 0;
      gasPrice = "";
      timestamp = 0L;
      category = 0;
      description = "";
      transactionRes = 0;
      blockNumber = 0L;
      txHash = "";
      errMsg = "";
      extraData = "";
      tid = 0;
      remark = "";
      addressAlias = "";
      tokenSymbol = "";
      tokenId = 0;
      tokenValue = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.billType != 0) {
        output.writeInt32(1, this.billType);
      }
      if (!this.transactionValue.equals("")) {
        output.writeString(2, this.transactionValue);
      }
      if (!this.transactionFrom.equals("")) {
        output.writeString(3, this.transactionFrom);
      }
      if (!this.transactionTo.equals("")) {
        output.writeString(4, this.transactionTo);
      }
      if (this.gasLimit != 0) {
        output.writeUInt32(5, this.gasLimit);
      }
      if (!this.gasPrice.equals("")) {
        output.writeString(6, this.gasPrice);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(7, this.timestamp);
      }
      if (this.category != 0) {
        output.writeInt32(8, this.category);
      }
      if (!this.description.equals("")) {
        output.writeString(9, this.description);
      }
      if (this.transactionRes != 0) {
        output.writeInt32(10, this.transactionRes);
      }
      if (this.blockNumber != 0L) {
        output.writeUInt64(11, this.blockNumber);
      }
      if (!this.txHash.equals("")) {
        output.writeString(12, this.txHash);
      }
      if (!this.errMsg.equals("")) {
        output.writeString(13, this.errMsg);
      }
      if (!this.extraData.equals("")) {
        output.writeString(14, this.extraData);
      }
      if (this.tid != 0) {
        output.writeInt32(15, this.tid);
      }
      if (!this.remark.equals("")) {
        output.writeString(16, this.remark);
      }
      if (!this.addressAlias.equals("")) {
        output.writeString(17, this.addressAlias);
      }
      if (!this.tokenSymbol.equals("")) {
        output.writeString(18, this.tokenSymbol);
      }
      if (this.tokenId != 0) {
        output.writeInt32(19, this.tokenId);
      }
      if (!this.tokenValue.equals("")) {
        output.writeString(20, this.tokenValue);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.billType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.billType);
      }
      if (!this.transactionValue.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.transactionValue);
      }
      if (!this.transactionFrom.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.transactionFrom);
      }
      if (!this.transactionTo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.transactionTo);
      }
      if (this.gasLimit != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.gasLimit);
      }
      if (!this.gasPrice.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.gasPrice);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(7, this.timestamp);
      }
      if (this.category != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.category);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.description);
      }
      if (this.transactionRes != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.transactionRes);
      }
      if (this.blockNumber != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(11, this.blockNumber);
      }
      if (!this.txHash.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.txHash);
      }
      if (!this.errMsg.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.errMsg);
      }
      if (!this.extraData.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.extraData);
      }
      if (this.tid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(15, this.tid);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(16, this.remark);
      }
      if (!this.addressAlias.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(17, this.addressAlias);
      }
      if (!this.tokenSymbol.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(18, this.tokenSymbol);
      }
      if (this.tokenId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(19, this.tokenId);
      }
      if (!this.tokenValue.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(20, this.tokenValue);
      }
      return size;
    }

    @Override
    public TransactionInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.billType = input.readInt32();
            break;
          }
          case 18: {
            this.transactionValue = input.readString();
            break;
          }
          case 26: {
            this.transactionFrom = input.readString();
            break;
          }
          case 34: {
            this.transactionTo = input.readString();
            break;
          }
          case 40: {
            this.gasLimit = input.readUInt32();
            break;
          }
          case 50: {
            this.gasPrice = input.readString();
            break;
          }
          case 56: {
            this.timestamp = input.readInt64();
            break;
          }
          case 64: {
            this.category = input.readInt32();
            break;
          }
          case 74: {
            this.description = input.readString();
            break;
          }
          case 80: {
            this.transactionRes = input.readInt32();
            break;
          }
          case 88: {
            this.blockNumber = input.readUInt64();
            break;
          }
          case 98: {
            this.txHash = input.readString();
            break;
          }
          case 106: {
            this.errMsg = input.readString();
            break;
          }
          case 114: {
            this.extraData = input.readString();
            break;
          }
          case 120: {
            this.tid = input.readInt32();
            break;
          }
          case 130: {
            this.remark = input.readString();
            break;
          }
          case 138: {
            this.addressAlias = input.readString();
            break;
          }
          case 146: {
            this.tokenSymbol = input.readString();
            break;
          }
          case 152: {
            this.tokenId = input.readInt32();
            break;
          }
          case 162: {
            this.tokenValue = input.readString();
            break;
          }
        }
      }
    }

    public static TransactionInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TransactionInfo(), data);
    }

    public static TransactionInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TransactionInfo().mergeFrom(input);
    }
  }

  public static final class UnitPrice extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UnitPrice[] _emptyArray;
    public static UnitPrice[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UnitPrice[0];
          }
        }
      }
      return _emptyArray;
    }

    // float value = 1;
    public float value;

    // int32 currencyType = 2;
    public int currencyType;

    public UnitPrice() {
      clear();
    }

    public UnitPrice clear() {
      value = 0F;
      currencyType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (Float.floatToIntBits(this.value)
          != Float.floatToIntBits(0F)) {
        output.writeFloat(1, this.value);
      }
      if (this.currencyType != 0) {
        output.writeInt32(2, this.currencyType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (Float.floatToIntBits(this.value)
          != Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(1, this.value);
      }
      if (this.currencyType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.currencyType);
      }
      return size;
    }

    @Override
    public UnitPrice mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 13: {
            this.value = input.readFloat();
            break;
          }
          case 16: {
            this.currencyType = input.readInt32();
            break;
          }
        }
      }
    }

    public static UnitPrice parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UnitPrice(), data);
    }

    public static UnitPrice parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UnitPrice().mergeFrom(input);
    }
  }

  public static final class DappBind extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DappBind[] _emptyArray;
    public static DappBind[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DappBind[0];
          }
        }
      }
      return _emptyArray;
    }

    // string appId = 1;
    public String appId;

    // string name = 2;
    public String name;

    // string iconUrl = 3;
    public String iconUrl;

    // string scheme = 4;
    public String scheme;

    // int32 state = 5;
    public int state;

    // string userId = 6;
    public String userId;

    // string address = 7;
    public String address;

    // bool autoTransaction = 8;
    public boolean autoTransaction;

    // string downloadUrl = 9;
    public String downloadUrl;

    // int32 dappType = 10;
    public int dappType;

    // string rewardTTC = 11;
    public String rewardTTC;

    // int32 rewardState = 12;
    public int rewardState;

    // int32 firstOfferRewardTime = 13;
    public int firstOfferRewardTime;

    // string popupUrl = 14;
    public String popupUrl;

    // int32 bindReward = 15;
    public int bindReward;

    // string symbol = 16;
    public String symbol;

    // string description = 17;
    public String description;

    public DappBind() {
      clear();
    }

    public DappBind clear() {
      appId = "";
      name = "";
      iconUrl = "";
      scheme = "";
      state = 0;
      userId = "";
      address = "";
      autoTransaction = false;
      downloadUrl = "";
      dappType = 0;
      rewardTTC = "";
      rewardState = 0;
      firstOfferRewardTime = 0;
      popupUrl = "";
      bindReward = 0;
      symbol = "";
      description = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.appId.equals("")) {
        output.writeString(1, this.appId);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      if (!this.iconUrl.equals("")) {
        output.writeString(3, this.iconUrl);
      }
      if (!this.scheme.equals("")) {
        output.writeString(4, this.scheme);
      }
      if (this.state != 0) {
        output.writeInt32(5, this.state);
      }
      if (!this.userId.equals("")) {
        output.writeString(6, this.userId);
      }
      if (!this.address.equals("")) {
        output.writeString(7, this.address);
      }
      if (this.autoTransaction != false) {
        output.writeBool(8, this.autoTransaction);
      }
      if (!this.downloadUrl.equals("")) {
        output.writeString(9, this.downloadUrl);
      }
      if (this.dappType != 0) {
        output.writeInt32(10, this.dappType);
      }
      if (!this.rewardTTC.equals("")) {
        output.writeString(11, this.rewardTTC);
      }
      if (this.rewardState != 0) {
        output.writeInt32(12, this.rewardState);
      }
      if (this.firstOfferRewardTime != 0) {
        output.writeInt32(13, this.firstOfferRewardTime);
      }
      if (!this.popupUrl.equals("")) {
        output.writeString(14, this.popupUrl);
      }
      if (this.bindReward != 0) {
        output.writeInt32(15, this.bindReward);
      }
      if (!this.symbol.equals("")) {
        output.writeString(16, this.symbol);
      }
      if (!this.description.equals("")) {
        output.writeString(17, this.description);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.appId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.appId);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      if (!this.iconUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.iconUrl);
      }
      if (!this.scheme.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.scheme);
      }
      if (this.state != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.state);
      }
      if (!this.userId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.userId);
      }
      if (!this.address.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.address);
      }
      if (this.autoTransaction != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.autoTransaction);
      }
      if (!this.downloadUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.downloadUrl);
      }
      if (this.dappType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.dappType);
      }
      if (!this.rewardTTC.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.rewardTTC);
      }
      if (this.rewardState != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.rewardState);
      }
      if (this.firstOfferRewardTime != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(13, this.firstOfferRewardTime);
      }
      if (!this.popupUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.popupUrl);
      }
      if (this.bindReward != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(15, this.bindReward);
      }
      if (!this.symbol.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(16, this.symbol);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(17, this.description);
      }
      return size;
    }

    @Override
    public DappBind mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.appId = input.readString();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
          case 26: {
            this.iconUrl = input.readString();
            break;
          }
          case 34: {
            this.scheme = input.readString();
            break;
          }
          case 40: {
            this.state = input.readInt32();
            break;
          }
          case 50: {
            this.userId = input.readString();
            break;
          }
          case 58: {
            this.address = input.readString();
            break;
          }
          case 64: {
            this.autoTransaction = input.readBool();
            break;
          }
          case 74: {
            this.downloadUrl = input.readString();
            break;
          }
          case 80: {
            this.dappType = input.readInt32();
            break;
          }
          case 90: {
            this.rewardTTC = input.readString();
            break;
          }
          case 96: {
            this.rewardState = input.readInt32();
            break;
          }
          case 104: {
            this.firstOfferRewardTime = input.readInt32();
            break;
          }
          case 114: {
            this.popupUrl = input.readString();
            break;
          }
          case 120: {
            this.bindReward = input.readInt32();
            break;
          }
          case 130: {
            this.symbol = input.readString();
            break;
          }
          case 138: {
            this.description = input.readString();
            break;
          }
        }
      }
    }

    public static DappBind parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DappBind(), data);
    }

    public static DappBind parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DappBind().mergeFrom(input);
    }
  }

  public static final class Dapp extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Dapp[] _emptyArray;
    public static Dapp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Dapp[0];
          }
        }
      }
      return _emptyArray;
    }

    // string appId = 1;
    public String appId;

    // string name = 2;
    public String name;

    // string iconUrl = 3;
    public String iconUrl;

    // string dappUrl = 4;
    public String dappUrl;

    // string description = 5;
    public String description;

    public Dapp() {
      clear();
    }

    public Dapp clear() {
      appId = "";
      name = "";
      iconUrl = "";
      dappUrl = "";
      description = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.appId.equals("")) {
        output.writeString(1, this.appId);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      if (!this.iconUrl.equals("")) {
        output.writeString(3, this.iconUrl);
      }
      if (!this.dappUrl.equals("")) {
        output.writeString(4, this.dappUrl);
      }
      if (!this.description.equals("")) {
        output.writeString(5, this.description);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.appId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.appId);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      if (!this.iconUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.iconUrl);
      }
      if (!this.dappUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.dappUrl);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.description);
      }
      return size;
    }

    @Override
    public Dapp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.appId = input.readString();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
          case 26: {
            this.iconUrl = input.readString();
            break;
          }
          case 34: {
            this.dappUrl = input.readString();
            break;
          }
          case 42: {
            this.description = input.readString();
            break;
          }
        }
      }
    }

    public static Dapp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Dapp(), data);
    }

    public static Dapp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Dapp().mergeFrom(input);
    }
  }

  public static final class KVInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile KVInfo[] _emptyArray;
    public static KVInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new KVInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // string key = 1;
    public String key;

    // string value = 2;
    public String value;

    public KVInfo() {
      clear();
    }

    public KVInfo clear() {
      key = "";
      value = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.key.equals("")) {
        output.writeString(1, this.key);
      }
      if (!this.value.equals("")) {
        output.writeString(2, this.value);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.key.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.key);
      }
      if (!this.value.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.value);
      }
      return size;
    }

    @Override
    public KVInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.key = input.readString();
            break;
          }
          case 18: {
            this.value = input.readString();
            break;
          }
        }
      }
    }

    public static KVInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new KVInfo(), data);
    }

    public static KVInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new KVInfo().mergeFrom(input);
    }
  }

  public static final class ActionInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ActionInfo[] _emptyArray;
    public static ActionInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // int32 actionType = 1;
    public int actionType;

    // string actionHash = 2;
    public String actionHash;

    // string fromUserId = 3;
    public String fromUserId;

    // int64 timestamp = 4;
    public long timestamp;

    // string extra = 5;
    public String extra;

    public ActionInfo() {
      clear();
    }

    public ActionInfo clear() {
      actionType = 0;
      actionHash = "";
      fromUserId = "";
      timestamp = 0L;
      extra = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.actionType != 0) {
        output.writeInt32(1, this.actionType);
      }
      if (!this.actionHash.equals("")) {
        output.writeString(2, this.actionHash);
      }
      if (!this.fromUserId.equals("")) {
        output.writeString(3, this.fromUserId);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(4, this.timestamp);
      }
      if (!this.extra.equals("")) {
        output.writeString(5, this.extra);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.actionType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.actionType);
      }
      if (!this.actionHash.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.actionHash);
      }
      if (!this.fromUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.fromUserId);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.timestamp);
      }
      if (!this.extra.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.extra);
      }
      return size;
    }

    @Override
    public ActionInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.actionType = input.readInt32();
            break;
          }
          case 18: {
            this.actionHash = input.readString();
            break;
          }
          case 26: {
            this.fromUserId = input.readString();
            break;
          }
          case 32: {
            this.timestamp = input.readInt64();
            break;
          }
          case 42: {
            this.extra = input.readString();
            break;
          }
        }
      }
    }

    public static ActionInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionInfo(), data);
    }

    public static ActionInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionInfo().mergeFrom(input);
    }
  }

  public static final class Order extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Order[] _emptyArray;
    public static Order[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Order[0];
          }
        }
      }
      return _emptyArray;
    }

    // string orderId = 1;
    public String orderId;

    // string outTradeNo = 2;
    public String outTradeNo;

    // string description = 3;
    public String description;

    // string totalFee = 4;
    public String totalFee;

    // string partnerAddress = 5;
    public String partnerAddress;

    // string partnerName = 6;
    public String partnerName;

    // int64 createTime = 7;
    public long createTime;

    // int64 expireTime = 8;
    public long expireTime;

    // int32 state = 9;
    public int state;

    // string txHash = 10;
    public String txHash;

    // uint32 payGasLimit = 11;
    public int payGasLimit;

    // string payGasPrice = 12;
    public String payGasPrice;

    // int32 tokenId = 13;
    public int tokenId;

    public Order() {
      clear();
    }

    public Order clear() {
      orderId = "";
      outTradeNo = "";
      description = "";
      totalFee = "";
      partnerAddress = "";
      partnerName = "";
      createTime = 0L;
      expireTime = 0L;
      state = 0;
      txHash = "";
      payGasLimit = 0;
      payGasPrice = "";
      tokenId = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.orderId.equals("")) {
        output.writeString(1, this.orderId);
      }
      if (!this.outTradeNo.equals("")) {
        output.writeString(2, this.outTradeNo);
      }
      if (!this.description.equals("")) {
        output.writeString(3, this.description);
      }
      if (!this.totalFee.equals("")) {
        output.writeString(4, this.totalFee);
      }
      if (!this.partnerAddress.equals("")) {
        output.writeString(5, this.partnerAddress);
      }
      if (!this.partnerName.equals("")) {
        output.writeString(6, this.partnerName);
      }
      if (this.createTime != 0L) {
        output.writeInt64(7, this.createTime);
      }
      if (this.expireTime != 0L) {
        output.writeInt64(8, this.expireTime);
      }
      if (this.state != 0) {
        output.writeInt32(9, this.state);
      }
      if (!this.txHash.equals("")) {
        output.writeString(10, this.txHash);
      }
      if (this.payGasLimit != 0) {
        output.writeUInt32(11, this.payGasLimit);
      }
      if (!this.payGasPrice.equals("")) {
        output.writeString(12, this.payGasPrice);
      }
      if (this.tokenId != 0) {
        output.writeInt32(13, this.tokenId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.orderId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.orderId);
      }
      if (!this.outTradeNo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.outTradeNo);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.description);
      }
      if (!this.totalFee.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.totalFee);
      }
      if (!this.partnerAddress.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.partnerAddress);
      }
      if (!this.partnerName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.partnerName);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(7, this.createTime);
      }
      if (this.expireTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.expireTime);
      }
      if (this.state != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.state);
      }
      if (!this.txHash.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.txHash);
      }
      if (this.payGasLimit != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(11, this.payGasLimit);
      }
      if (!this.payGasPrice.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.payGasPrice);
      }
      if (this.tokenId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(13, this.tokenId);
      }
      return size;
    }

    @Override
    public Order mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.orderId = input.readString();
            break;
          }
          case 18: {
            this.outTradeNo = input.readString();
            break;
          }
          case 26: {
            this.description = input.readString();
            break;
          }
          case 34: {
            this.totalFee = input.readString();
            break;
          }
          case 42: {
            this.partnerAddress = input.readString();
            break;
          }
          case 50: {
            this.partnerName = input.readString();
            break;
          }
          case 56: {
            this.createTime = input.readInt64();
            break;
          }
          case 64: {
            this.expireTime = input.readInt64();
            break;
          }
          case 72: {
            this.state = input.readInt32();
            break;
          }
          case 82: {
            this.txHash = input.readString();
            break;
          }
          case 88: {
            this.payGasLimit = input.readUInt32();
            break;
          }
          case 98: {
            this.payGasPrice = input.readString();
            break;
          }
          case 104: {
            this.tokenId = input.readInt32();
            break;
          }
        }
      }
    }

    public static Order parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Order(), data);
    }

    public static Order parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Order().mergeFrom(input);
    }
  }
}
